name: build page and deploy page and maps

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: setup environment
        run: |
          sudo gem install bundler:2.2.6

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master

      # Build jekyll page
      - run: |
          bundle config path vendor/bundle
          bundle install
          bundle exec jekyll build

      - name: upload
        if: github.event_name == 'push'
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${SSH_KEY}"
          mkdir ~/.ssh
          ssh-keyscan -H ${SSH_HOST}  >> ~/.ssh/known_hosts
          rsync -avz '-e ssh -o StrictHostKeyChecking=no' _site/ "${SSH_USER}@${SSH_HOST}:/world.naturkunde.museum"
